from typing import Any, Awaitable, Callable, FrozenSet, Iterable, Mapping, Optional, Sequence, Type, Union
from ._types import AuthLike, Body, ContentCallback, CookiesLike, HeadersLike, Hooks, HttpVersion, Impersonate, ParamsLike, Proxies, Retry, Timeout, Verify
from .impersonate import ExtraFingerprints
from .models import AsyncResponse, PreparedRequest, Request, Response
from .multipart import CurlMime
from .websockets import AsyncWebSocket, WebSocket

class RetryStrategy:
    count: int
    delay: float
    jitter: float
    backoff: str
    codes: FrozenSet[int]
    def __init__(self, count: int, delay: float = ..., jitter: float = ..., backoff: str = ..., codes: Iterable[int] = ...) -> None: ...
    @classmethod
    def coerce(cls, value: Optional[Union[int, RetryStrategy]]) -> RetryStrategy: ...
    def sleep_for(self, attempt: int) -> float: ...
    def should_retry_status(self, status_code: int) -> bool: ...

class BaseSession:
    headers: Any
    cookies: Any
    proxies: Mapping[str, Optional[str]]
    impersonate: Optional[str]
    http_version: Optional[str]
    timeout: Optional[Timeout]
    def __init__(self, impersonate: Optional[Impersonate] = ..., proxy: Optional[str] = ..., proxies: Optional[Proxies] = ..., proxy_auth: Optional[AuthLike] = ..., verify: Verify = ..., timeout: Optional[Timeout] = ..., headers: Optional[HeadersLike] = ..., cookies: Optional[CookiesLike] = ..., params: Optional[ParamsLike] = ..., auth: Optional[AuthLike] = ..., cert: Any = ..., stream: bool = ..., hooks: Optional[Hooks] = ..., max_redirects: int = ..., trust_env: bool = ..., allow_redirects: bool = ..., max_response_bytes: Optional[int] = ..., base_url: Optional[str] = ..., http_version: Optional[HttpVersion] = ..., ja3: Optional[str] = ..., akamai: Optional[str] = ..., perk: Optional[str] = ..., extra_fp: Optional[Union[ExtraFingerprints, Mapping[str, Any]]] = ..., default_headers: bool = ..., default_encoding: str = ..., discard_cookies: bool = ..., raise_for_status: bool = ..., retry: Retry = ..., cache: bool = ..., user_agent: Optional[str] = ..., accept_language: Optional[str] = ..., interface: Optional[str] = ..., doh_url: Optional[str] = ..., max_recv_speed: int = ..., curl_options: Optional[Mapping[Any, Any]] = ..., max_engines: int = ..., response_class: Optional[Type[Response]] = ...) -> None: ...
    def mount(self, prefix: str, adapter: Any) -> None: ...
    def get_adapter(self, url: str) -> Any: ...
    def prepare_request(self, request: Request) -> PreparedRequest: ...
    def close(self) -> None: ...

class Session(BaseSession):
    def request(self, method: str, url: str, params: Optional[ParamsLike] = ..., data: Optional[Body] = ..., headers: Optional[HeadersLike] = ..., cookies: Optional[CookiesLike] = ..., files: Any = ..., auth: Optional[AuthLike] = ..., timeout: Optional[Timeout] = ..., allow_redirects: bool = ..., proxies: Optional[Proxies] = ..., hooks: Optional[Hooks] = ..., stream: Optional[bool] = ..., verify: Optional[Verify] = ..., cert: Any = ..., json: Any = ..., content: Optional[Body] = ..., multipart: Optional[CurlMime] = ..., impersonate: Optional[Impersonate] = ..., proxy: Optional[str] = ..., http_version: Optional[HttpVersion] = ..., max_redirects: Optional[int] = ..., max_response_bytes: Optional[int] = ..., referer: Optional[str] = ..., accept_encoding: Optional[str] = ..., default_encoding: Optional[str] = ..., discard_cookies: Optional[bool] = ..., retry: Optional[Retry] = ..., cache_mode: Any = ..., priority: Optional[int] = ..., ja3: Optional[str] = ..., akamai: Optional[str] = ..., perk: Optional[str] = ..., extra_fp: Optional[Union[ExtraFingerprints, Mapping[str, Any]]] = ..., content_callback: Optional[ContentCallback] = ..., raise_for_status: Optional[bool] = ..., quote: Optional[bool] = ..., curl_options: Optional[Mapping[Any, Any]] = ..., interface: Optional[str] = ..., doh_url: Optional[str] = ..., max_recv_speed: Optional[int] = ..., thread: Any = ..., debug: Any = ...) -> Response: ...
    def send(self, request: PreparedRequest, **options: Any) -> Response: ...
    def get(self, url: str, params: Optional[ParamsLike] = ..., **kwargs: Any) -> Response: ...
    def options(self, url: str, **kwargs: Any) -> Response: ...
    def head(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, data: Optional[Body] = ..., json: Any = ..., **kwargs: Any) -> Response: ...
    def put(self, url: str, data: Optional[Body] = ..., **kwargs: Any) -> Response: ...
    def patch(self, url: str, data: Optional[Body] = ..., **kwargs: Any) -> Response: ...
    def delete(self, url: str, **kwargs: Any) -> Response: ...
    def trace(self, url: str, **kwargs: Any) -> Response: ...
    def query(self, url: str, **kwargs: Any) -> Response: ...
    def websocket(self, url: str, origin: str = ..., headers: Optional[HeadersLike] = ..., timeout: Optional[Timeout] = ..., proxy: Optional[str] = ..., proxies: Optional[Proxies] = ..., impersonate: Optional[Impersonate] = ..., protocols: Optional[Sequence[str]] = ..., verify: Optional[Verify] = ...) -> WebSocket: ...
    ws_connect: Callable[..., WebSocket]
    def __enter__(self) -> Session: ...
    def __exit__(self, *exc: Any) -> None: ...

class AsyncSession(BaseSession):
    max_clients: Optional[int]
    def __init__(self, impersonate: Optional[Impersonate] = ..., proxy: Optional[str] = ..., proxies: Optional[Proxies] = ..., proxy_auth: Optional[AuthLike] = ..., verify: Verify = ..., timeout: Optional[Timeout] = ..., headers: Optional[HeadersLike] = ..., cookies: Optional[CookiesLike] = ..., params: Optional[ParamsLike] = ..., auth: Optional[AuthLike] = ..., cert: Any = ..., stream: bool = ..., hooks: Optional[Hooks] = ..., max_redirects: int = ..., trust_env: bool = ..., allow_redirects: bool = ..., max_response_bytes: Optional[int] = ..., base_url: Optional[str] = ..., http_version: Optional[HttpVersion] = ..., ja3: Optional[str] = ..., akamai: Optional[str] = ..., perk: Optional[str] = ..., extra_fp: Optional[Union[ExtraFingerprints, Mapping[str, Any]]] = ..., default_headers: bool = ..., default_encoding: str = ..., discard_cookies: bool = ..., raise_for_status: bool = ..., retry: Retry = ..., cache: bool = ..., user_agent: Optional[str] = ..., accept_language: Optional[str] = ..., interface: Optional[str] = ..., doh_url: Optional[str] = ..., max_recv_speed: int = ..., curl_options: Optional[Mapping[Any, Any]] = ..., max_engines: int = ..., response_class: Optional[Type[AsyncResponse]] = ..., max_clients: Optional[int] = ...) -> None: ...
    async def request(self, method: str, url: str, params: Optional[ParamsLike] = ..., data: Optional[Body] = ..., headers: Optional[HeadersLike] = ..., cookies: Optional[CookiesLike] = ..., files: Any = ..., auth: Optional[AuthLike] = ..., timeout: Optional[Timeout] = ..., allow_redirects: bool = ..., proxies: Optional[Proxies] = ..., hooks: Optional[Hooks] = ..., stream: Optional[bool] = ..., verify: Optional[Verify] = ..., cert: Any = ..., json: Any = ..., content: Optional[Body] = ..., multipart: Optional[CurlMime] = ..., impersonate: Optional[Impersonate] = ..., proxy: Optional[str] = ..., http_version: Optional[HttpVersion] = ..., max_redirects: Optional[int] = ..., max_response_bytes: Optional[int] = ..., referer: Optional[str] = ..., accept_encoding: Optional[str] = ..., default_encoding: Optional[str] = ..., discard_cookies: Optional[bool] = ..., retry: Optional[Retry] = ..., cache_mode: Any = ..., priority: Optional[int] = ..., ja3: Optional[str] = ..., akamai: Optional[str] = ..., perk: Optional[str] = ..., extra_fp: Optional[Union[ExtraFingerprints, Mapping[str, Any]]] = ..., content_callback: Optional[ContentCallback] = ..., raise_for_status: Optional[bool] = ..., quote: Optional[bool] = ..., curl_options: Optional[Mapping[Any, Any]] = ..., interface: Optional[str] = ..., doh_url: Optional[str] = ..., max_recv_speed: Optional[int] = ..., thread: Any = ..., debug: Any = ...) -> AsyncResponse: ...
    async def send(self, request: PreparedRequest, **options: Any) -> AsyncResponse: ...
    async def get(self, url: str, params: Optional[ParamsLike] = ..., **kwargs: Any) -> AsyncResponse: ...
    async def options(self, url: str, **kwargs: Any) -> AsyncResponse: ...
    async def head(self, url: str, **kwargs: Any) -> AsyncResponse: ...
    async def post(self, url: str, data: Optional[Body] = ..., json: Any = ..., **kwargs: Any) -> AsyncResponse: ...
    async def put(self, url: str, data: Optional[Body] = ..., **kwargs: Any) -> AsyncResponse: ...
    async def patch(self, url: str, data: Optional[Body] = ..., **kwargs: Any) -> AsyncResponse: ...
    async def delete(self, url: str, **kwargs: Any) -> AsyncResponse: ...
    async def trace(self, url: str, **kwargs: Any) -> AsyncResponse: ...
    async def query(self, url: str, **kwargs: Any) -> AsyncResponse: ...
    async def websocket(self, url: str, origin: str = ..., headers: Optional[HeadersLike] = ..., timeout: Optional[Timeout] = ..., proxy: Optional[str] = ..., proxies: Optional[Proxies] = ..., impersonate: Optional[Impersonate] = ..., protocols: Optional[Sequence[str]] = ..., verify: Optional[Verify] = ...) -> AsyncWebSocket: ...
    ws_connect: Callable[..., Awaitable[AsyncWebSocket]]
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> AsyncSession: ...
    async def __aexit__(self, *exc: Any) -> None: ...

Client = Session
AsyncClient = AsyncSession

def proxy_from_proxies(url: str, proxies: Optional[Proxies]) -> Optional[str]: ...
def merge_setting(request_setting: Any, session_setting: Any, dict_class: Type[Any] = ...) -> Any: ...
