// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteRequest {
    /// The unique identifier for this request (for tracing).
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// The target HTTP request details.
    #[prost(message, optional, tag = "2")]
    pub target: ::core::option::Option<TargetRequest>,
    /// Configuration for how this request should be executed.
    #[prost(message, optional, tag = "3")]
    pub config: ::core::option::Option<ExecutionConfig>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TargetRequest {
    /// e.g., "GET", "POST"
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    /// Ordered headers list - preserves insertion order
    #[prost(message, repeated, tag = "3")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
    /// Body of the request.
    /// For JSON requests to this service, send base64 encoded string if strictly using JSON.
    #[prost(bytes = "vec", tag = "4")]
    #[serde(with = "hex::serde")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
/// Single header with name and value
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Header {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionConfig {
    /// Timeout in milliseconds.
    #[prost(uint32, tag = "1")]
    pub timeout_ms: u32,
    /// Whether to automatically follow HTTP redirects.
    #[prost(bool, tag = "2")]
    pub follow_redirects: bool,
    /// Optional proxy configuration.
    #[prost(message, optional, tag = "3")]
    pub proxy: ::core::option::Option<ProxyConfig>,
    /// If set to true, SSL certificate verification will be skipped.
    /// WARNING: This is insecure and should only be used for testing purposes.
    #[prost(bool, tag = "4")]
    pub skip_cert_verify: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxyConfig {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
    /// Optional authentication.
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
    #[prost(enumeration = "proxy_config::ProxyType", tag = "5")]
    pub r#type: i32,
}
/// Nested message and enum types in `ProxyConfig`.
pub mod proxy_config {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ProxyType {
        Http = 0,
        Https = 1,
        Socks5 = 2,
    }
    impl ProxyType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Http => "HTTP",
                Self::Https => "HTTPS",
                Self::Socks5 => "SOCKS5",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "HTTP" => Some(Self::Http),
                "HTTPS" => Some(Self::Https),
                "SOCKS5" => Some(Self::Socks5),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// True if the network call was attempted (even if it returned 404/500).
    /// False if internal engine error occurred.
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// Error message if success is false.
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
    /// The HTTP response details.
    #[prost(message, optional, tag = "4")]
    pub response: ::core::option::Option<TargetResponse>,
    /// Time taken for the request in milliseconds.
    #[prost(int64, tag = "5")]
    pub duration_ms: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TargetResponse {
    #[prost(int32, tag = "1")]
    pub status_code: i32,
    #[prost(map = "string, message", tag = "2")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        HeaderValues,
    >,
    #[prost(bytes = "vec", tag = "3")]
    #[serde(with = "hex::serde")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeaderValues {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
